import { useState, useCallback, useEffect } from "react";
import type { VideoFile } from "../../types";
import { useFFmpeg } from "../../hooks/useFFmpeg";
import { useTranslation } from "../../context/LanguageContext";
import ProcessingOverlay from "../common/ProcessingOverlay";
import DownloadButton from "../common/DownloadButton";

interface CompressPanelProps {  video: VideoFile;}const PRESETS = [  { label: "Ultra Fast", value: "ultrafast" },  { label: "Fast", value: "fast" },  { label: "Medium", value: "medium" },  { label: "Slow", value: "slow" },  { label: "Very Slow", value: "veryslow" },];
export default function CompressPanel({ video }: CompressPanelProps) {
  const { init, run, cancel, progress, log, loaded, loading, error, cancelling, running } = useFFmpeg();  const { t } = useTranslation();
  const [crf, setCrf] = useState(23);
  const [preset, setPreset] = useState("medium");
  const [outputUrl, setOutputUrl] = useState<string | null>(null);

  const [outputBlob, setOutputBlob] = useState<Blob | null>(null);  useEffect(() => { init(); }, [init]);  const handleCompress = useCallback(async () => {    setOutputUrl(null);    await run(async (instance) => {      if (!video.data) throw new Error("No video data loaded");      const ext = video.name.match(/\.[^.]+$/)?.[0] || ".mp4";      const inputName = "input" + ext;      const outputName = "compressed" + ext;      await instance.writeFile(inputName, video.data);      await instance.exec([        "-i", inputName,        "-c:v", "libx264",        "-crf", String(crf),        "-preset", preset,        "-c:a", "aac",        "-movflags", "+faststart",        "-y", outputName,      ]);      const raw = await instance.readFile(outputName);      const blob = new Blob([raw as BlobPart], { type: "video/mp4" });      setOutputBlob(blob);
      setOutputUrl(URL.createObjectURL(blob));
    });
  }, [video.data, video.name, crf, preset, run]);
  return (    <div className="card space-y-6">      <div>        <label className="block text-sm text-surface-400 mb-1">          {t("compress.crf")}: {crf} ({crf <= 18 ? t("compress.high_quality") : crf <= 28 ? t("compress.balanced") : t("compress.small_size")})        </label>        <input type="range" min={18} max={51} value={crf} onChange={(e) => setCrf(Number(e.target.value))} className="input-range" />        <div className="flex justify-between text-xs text-surface-500 mt-1">          <span>{t("compress.high_quality")} (18)</span>          <span>{t("compress.small_size")} (51)</span>        </div>      </div>      <div>        <label className="block text-sm text-surface-400 mb-1">{t("compress.preset")}</label>        <select value={preset} onChange={(e) => setPreset(e.target.value)} className="select-input w-full">          {PRESETS.map((p) => <option key={p.value} value={p.value}>{p.label}</option>)}        </select>        <p className="text-xs text-surface-600 mt-1">{t("compress.preset_hint")}</p>      </div>      <ProcessingOverlay active={running} progress={progress} label={t("compress.compressing")} log={log} onCancel={cancel} cancelling={cancelling} />      {error && <div className="banner-error">{error}</div>}      <div className="flex gap-3">        <button onClick={handleCompress} disabled={loading || running} className="btn-primary">          {!loaded ? t("common.load_ffmpeg") : t("compress.compress")}        </button>        {outputUrl && outputBlob && <DownloadButton blob={outputBlob} filename={video.name.replace(/\.[^.]+$/, "") + "_compressed.mp4"} filters={[{ name: "MP4 Video", extensions: ["mp4"] }]} label={t("common.download")} />}      </div>    </div>  );}